### ISSUE TITLE
Needs guidance on error handling

### ISSUE THREAD

**Issue by mwrites** [argentlabs/web3.swift#204]
Hello,

I have noticed most of the `EthereumClient` errors are wrapped into [`EthereumClientError.unexpectedReturnValue`](https://github.com/argentlabs/web3.swift/blob/769762fdc544734ffe5eabc9e7d1c42260bd9be3/web3swift/src/Client/EthereumClient.swift#L307).

Althought `EthereumRPC` handle and parse [the errors properly](https://github.com/argentlabs/web3.swift/blob/769762fdc544734ffe5eabc9e7d1c42260bd9be3/web3swift/src/Client/JSONRPC.swift#L87). On the upper layer they are all hidden into the generic `EthereumClientError.unexpectedReturnValue`.

What do you think would be a good way to propagate these underlying errors? I am trying to figure out how to properly make these errors flow to the UI layer so that I can give a proper reason to the user on why the transaction failed. Typically, the most common issues would be not enough eth to pay for transaction value or gas but could be anything more.

I considered adding an associated string to the `EthereumClientError.unexpectedReturnValue` enum but this would basically change the whole EthereumClient api. Do you guys get the the transaction errors by querying the logs directly or in some other way?

Great job on the library thanks!

**Comment by dnKaratzas** [comment]
Now I think in most cases will return you JSONRPCError.executionError which you can get the code and the message. @DarthMike am I right?

**Comment by DarthMike** [comment]
@mwrites Recently fixed this with  #120 and #207
The APIs now give back the error to the caller correctly.

**Comment by mwrites** [comment]
Awesome, thanks!

**Comment by luca992** [comment]
I tried the dev branch and errors are still not being propagated. I'm still getting `unexpectedReturnValue` for `eth_estimateGas` requests. This is the error log from ganache which gets returned by web3.swift as `unexpectedReturnValue`:

```
[2:24:03 PM] eth_estimateGas
[2:24:03 PM]    > {
[2:24:03 PM]    >   "jsonrpc": "2.0",
[2:24:03 PM]    >   "method": "eth_estimateGas",
[2:24:03 PM]    >   "id": 1,[2:24:03 PM]    >   "params": [
[2:24:03 PM]    >     {
[2:24:03 PM]    >       "data": "0x64edfbf0",
[2:24:03 PM]    >       "to": "0xe7ab4dc4aca2c06f475a3743f2ab316a8b983c77",
[2:24:03 PM]    >       "gas": "0x989680",
[2:24:03 PM]    >       "gasPrice": "0x0",
[2:24:03 PM]    >       "from": "0x2ad093bad5b62f51a2145b87bb0f2295b1f9d4fd"[2:24:03 PM]    >     }
[2:24:03 PM]    >   ]
[2:24:03 PM]    > }
[2:24:03 PM]  <   {
[2:24:03 PM]  <     "id": 1,[2:24:03 PM]  <     "jsonrpc": "2.0",[2:24:03 PM]  <     "error": {
[2:24:03 PM]  <       "message": "VM Exception while processing transaction: revert Incorrect purchase amount sent",[2:24:03 PM]  <       "code": -32000,
[2:24:03 PM]  <       "data": {
[2:24:03 PM]  <         "stack": "RuntimeError: VM Exception while processing transaction: revert Incorrect purchase amount sent\n    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at module.exports (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/gas/guestimation.js:142:32)",
[2:24:03 PM]  <         "name": "RuntimeError"
[2:24:03 PM]  <       }
[2:24:03 PM]  <     }
[2:24:03 PM]  <   }
```
