### ISSUE TITLE
 unexpectedReturnValue for eth_estimateGas and eth_sendRawTransaction

### ISSUE THREAD

**Issue by luca992** [argentlabs/web3.swift#224]
I am trying to estimate gas and execute a execute a function in an ERC721 contract defined as:
```
function mint(address recipient, string memory uri, uint256 purchasePrice) public returns(uint256)
```

Both eth_estimateGas and eth_sendRawTransaction are returning errors as `unexpectedReturnValue`

Here's an example of eth_estimateGas. I am creating the client and calling the function like:

```
        let ethereumClient : EthereumClient = EthereumClient(url: URL(string: "http://0.0.0.0:7545/")!) // ganache
        let purchasePrice = BigUInt.init("10000000000000000")!
        let contractAddress = EthereumAddress("0xvalidContractAddress")
        let function = Mint(
            contract: contractAddress,
            from: ethereumAccount.address,
            uri: "https://ipfs.infura.io/ipfs/someEndpoint",
            purchasePrice: purchasePrice
        )
        let transaction = try! function.transaction()
        ethereumClient.eth_estimateGas(
            transaction,
            withAccount: ethereumAccount,
            completion: { error, estimate in
                print(ethereumClient)
                onComplete(error, estimate?.web3.hexString)
            }
        )
        ERC721.init(client: ethereumClient).balanceOf(contract: contractAddress, address: ethereumAccount.address, completion: { error, result in
                print(ethereumClient)
                print("erc721 balanceOf result \(result)")
                print("erc721  balanceOf error \(error)")
            })

```

```
public struct Mint: ABIFunction {
    public static let name = "mint"
    public let gasPrice: BigUInt? = nil
    public let gasLimit: BigUInt? = nil
    public var contract: EthereumAddress
    public let from: EthereumAddress?

    public let uri: String
    public let purchasePrice: BigUInt

    public init(contract: EthereumAddress,
                from: EthereumAddress? = nil,
                uri: String,
                purchasePrice: BigUInt) {
        self.contract = contract
        self.from = from
        self.uri = uri
        self.purchasePrice = purchasePrice
    }

    public func encode(to encoder: ABIFunctionEncoder) throws {
        try encoder.encode(from!)
        try encoder.encode(uri)
        try encoder.encode(purchasePrice)
    }
}
```

When running it prints:

```
eth_estimateGas estimate nil
eth_estimateGas error Optional(web3.EthereumClientError.unexpectedReturnValue)

erc721 balanceOf result Optional(1)
erc721  balanceOf error nil
```

There's clearly not a problem with the EthereumClient setup, because calling ERC721.balanceOf returns the count as expected. So there's clearly something wrong with how I am calling the function. Any idea what I am doing wrong?

**Comment by luca992** [comment]
So I think I found the issue. This is a failed eth_estimateGas from ganache logs.

```
[1:18:42 AM] eth_estimateGas
[1:18:42 AM]    > {
[1:18:42 AM]    >   "jsonrpc": "2.0",
[1:18:42 AM]    >   "method": "eth_estimateGas",
[1:18:42 AM]    >   "id": 1,
[1:18:42 AM]    >   "params": 
[[1:18:42 AM]    >     {
[1:18:42 AM]    >       "data": "0xba7aef430000000000000000000000002ad093bad5b62f51a2145b87bb0f2295b1f9d4fd0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000004a68747470733a2f2f697066732e696e667572612e696f2f697066732f516d5045467262397143465a476879357a51765258484362426a434a4d764d55736638514a786443696f3442706200000000000000000000000000000000000000000000",
[1:18:42 AM]    >       "to": "0x7d9ee5f4553f441441eb20dcfef048a4014186c3",
[1:18:42 AM]    >       "gas": "0x0",
[1:18:42 AM]    >       "gasPrice": "0x0",
[1:18:42 AM]    >       "from": "0x2ad093bad5b62f51a2145b87bb0f2295b1f9d4fd"
[1:18:42 AM]    >     }
[1:18:42 AM]    >   ]
[1:18:42 AM]    > }
[1:18:42 AM]  <   {
[1:18:42 AM]  <     "id": 1,
[1:18:42 AM]  <     "jsonrpc": "2.0",
[1:18:42 AM]  <     "result": "0x0000000000000000000000000000000000000000000000000000000000000001"[1:18:42 AM]  <   }
[1:18:42 AM]  <   {
[1:18:42 AM]  <     "id": 1,
[1:18:42 AM]  <     "jsonrpc": "2.0",
[1:18:42 AM]  <     "error": {
[1:18:42 AM]  <       "message": "base fee exceeds gas limit",
[1:18:42 AM]  <       "code": -32000,
[1:18:42 AM]  <       "data": {
[1:18:42 AM]  <         "stack": "Error: base fee exceeds gas limit\n    at VM.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-vm/lib/runTx.ts:107:11)\n    at step (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:33:23)\n    at Object.next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:14:53)\n    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
[1:18:42 AM]  <         "name": "Error"
[1:18:42 AM]  <       }
[1:18:42 AM]  <     }
[1:18:42 AM]  <   }
```
It is saying `base fee exceeds gas limit`. Which is due to `"gas": "0x0"` being included in the request.

When I run estimate gas using the [Web3j](https://docs.web3j.io/) library in java. It does not include those parameters at all. 

I was just able to get the eth_estimateGas working in web3.swift by setting a high gas limit:

```
let transaction = try! function.transaction( gasLimit: BigUInt.init("10000000")!)
```

However, I think this is a bug. When gasLimit and gasPrice aren't set by a transaction I think they should not be included in the jsonrpc request. i.e.  `"gas": "0x0",` `"gasPrice": "0x0",` should not be there

**Comment by dnKaratzas** [comment]
You are right. We must not include gas & gasPrice to request. Opened a PR that fixes that issue. Regarding the error parsing I will try to reproduce the bug and see what is going on

**Comment by dnKaratzas** [comment]
I reproduces the issue and the error is handled correctly:
<img width="1172" alt="Screenshot at Jun 06 11-49-33" src="https://user-images.githubusercontent.com/7944881/172128615-ed58d450-9867-466f-80a5-70ca726b0525.png">

**Comment by dnKaratzas** [comment]
Could you add breakpoints like I did to see how it parses the error?
